import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import '@fontsource/vazirmatn/400.css';
import '@fontsource/vazirmatn/500.css';
import '@fontsource/vazirmatn/600.css';
import '@fontsource/vazirmatn/700.css';
import '@fontsource/vazirmatn/800.css';
import '@fontsource/vazirmatn/900.css';
import './index.css';
import App from './App.tsx';
import { ErrorBoundary } from './components/ErrorBoundary.tsx';
import { preloadAllAssets } from './utils/assetPreloader';

// 1. Mount React application inside ErrorBoundary first
const rootElement = document.getElementById('root');
if (rootElement) {
  createRoot(rootElement).render(
    <StrictMode>
      <ErrorBoundary>
        <App />
      </ErrorBoundary>
    </StrictMode>
  );
}

// 2. Preload game assets in background after UI is mounted
if (typeof window !== 'undefined') {
  const schedulePreload = () => {
    try {
      preloadAllAssets();
    } catch (preloadErr) {
      console.warn('[Assets] Preload warning:', preloadErr);
    }
  };

  if ('requestIdleCallback' in window) {
    (window as any).requestIdleCallback(schedulePreload, { timeout: 3000 });
  } else {
    setTimeout(schedulePreload, 2000);
  }
}

// 3. Register Service Worker for Android notifications and offline support
if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
  window.addEventListener('load', async () => {
    try {
      // In dev mode or standalone notification support, register notification-sw.js directly
      // In production builds, register /sw.js generated by VitePWA
      const swUrl = import.meta.env.DEV ? '/notification-sw.js' : '/sw.js';
      const swOptions: RegistrationOptions = {
        scope: '/',
      };

      let registration = await navigator.serviceWorker.register(swUrl, swOptions);
      console.log('[PWA] Service Worker registered successfully:', registration.scope);

      // Check for updates
      registration.update().catch(() => {});

      registration.addEventListener('updatefound', () => {
        const newWorker = registration.installing;
        if (newWorker) {
          newWorker.addEventListener('statechange', () => {
            if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
              console.log('[PWA] Service Worker updated and ready.');
            }
          });
        }
      });
    } catch (err) {
      console.warn('[PWA] Primary Service Worker registration failed, trying fallback to /notification-sw.js:', err);
      try {
        await navigator.serviceWorker.register('/notification-sw.js', { scope: '/' });
        console.log('[PWA] Fallback notification-sw.js registered successfully');
      } catch (fallbackErr) {
        console.warn('[PWA] Service Worker could not be registered:', fallbackErr);
      }
    }
  });
}

